services:
  tux-senha:
    image: carandre/linuxtips-tux-senhas:1.0
    ports:
      - "5000:5000"
    networks:
      - tux
    environment:
      REDIS_HOST: redis

  redis:
    image: carandre/linuxtips-redis:1.0
    ports:
      - "6379:6379"
    networks:
      - tux
    volumes:
      - tux:/tux

networks:
  tux:
    driver: bridge

volumes:
  tux:
