services:
  giropops-senha:
    image: carandre/linuxtips-giropops-senhas:1.0
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis

  redis:
    image: carandre/linuxtips-redis:1.0
    ports:
      - "6379:6379"
    networks:
      - giropops
    volumes:
      - strigus:/strigus

networks:
  giropops:
    driver: bridge

volumes:
  strigus: