services:
  redis:
    image: carandre/linuxtips-redis:1.0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 30s
      timeout: 5s
      interval: 20s
      retries: 3
    networks:
      - tux
    volumes:
      - tux:/tux

networks:
  tux:
    driver: bridge

volumes:
  tux:
